inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  CountAsOne: [array, heredoc, hash] # method_call
  Max: 200
Metrics/MethodLength:
  Max: 20
Gemspec/AddRuntimeDependency:
  Enabled: false # https://github.com/rubocop/rubocop/pull/13030#discussion_r1674791776
